import { randomUUID } from "crypto";

const CAT_ORDER: Record<string, number> = {
  "FEIRA": 1, "VERDURÃO": 2, "DR SHAPE": 3, "ATACADÃO": 4, "MERCADO": 5,
  "VÂNIA": 6, "CLORO E CIA": 7, "BEBIDAS": 8, "OUTROS": 9, "DEPOSITO": 10,
  "PEDRO": 11, "DINE": 12, "LUIZ": 13, "SERTÃO NATURAL": 14, "ESTOQUE DE INSUMOS": 15,
};

export type ProdutoSeed = { nome: string; categoria: string; unidade: string; meta: number; restaurante: string };

export const JACOBINA: ProdutoSeed[] = [
  // COZINHA
  { nome:"Laranja", categoria:"FEIRA", unidade:"KG", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Repolho branco", categoria:"FEIRA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Repolho roxo", categoria:"FEIRA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Cenoura", categoria:"FEIRA", unidade:"KG", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Banana da terra", categoria:"FEIRA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Cebola branca", categoria:"FEIRA", unidade:"KG", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Tomate maduros e firmes", categoria:"FEIRA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Batatinha", categoria:"FEIRA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Brócolis", categoria:"FEIRA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Morango fresco", categoria:"FEIRA", unidade:"KG", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Coentro", categoria:"VERDURÃO", unidade:"PÉS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Pimentão vermelho", categoria:"VERDURÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Pimentão verde", categoria:"VERDURÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Alface", categoria:"VERDURÃO", unidade:"PÉS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Castanha", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Castanha triturada", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Cominho", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Orégano", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Pimenta do reino", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Canela em pó", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Lemon pepper", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Corante", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Açúcar", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Óleo", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Farinha de trigo", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Arroz", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Papel toalha", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Bombril", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Leite", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Presunto", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Extrato elefante", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Maionese", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Café", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Macarrão ninho", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sorvete", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Ovos", categoria:"MERCADO", unidade:"PLACAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Veja", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Vinagre", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Isqueiro", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Feijão", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Caldo de legumes", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Nescal", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sal", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Caldo de galinha Knorr", categoria:"MERCADO", unidade:"TABLETS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Fermento químico", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Embalagem rolinho", categoria:"VÂNIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Saco de congelamento 1kg", categoria:"VÂNIA", unidade:"BOBINA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Saco de congelamento 5kg", categoria:"VÂNIA", unidade:"BOBINA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Calda de chocolate para sorvete", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Plástico filme grande", categoria:"VÂNIA", unidade:"BOBINA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Cereja", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Bicarbonato de sódio", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Toucas", categoria:"VÂNIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Luva P", categoria:"VÂNIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Luvas M", categoria:"VÂNIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Luvas G", categoria:"VÂNIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Luvas GG", categoria:"VÂNIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Doce de leite", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Corante vermelho bordô em pó", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Chocolate em barra", categoria:"VÂNIA", unidade:"BARRA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Chocolate ao leite em barra", categoria:"VÂNIA", unidade:"BARRA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Amido de milho", categoria:"VÂNIA", unidade:"KG", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Essência de baunilha", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Chocolate 70%", categoria:"VÂNIA", unidade:"BARRA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Papel manteiga", categoria:"VÂNIA", unidade:"ROLO", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Saco de confeiteiro", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Açúcar refinado", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Catchup", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Garfo descartável reforçado", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Faca descartável reforçada", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Pote de 530ml com tampa", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Caneta em gel", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Desengordurante", categoria:"CLORO E CIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Desincrustante", categoria:"CLORO E CIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Vela de aniversário", categoria:"CLORO E CIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Fibraço", categoria:"CLORO E CIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Queijo", categoria:"OUTROS", unidade:"BARRA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Carne", categoria:"OUTROS", unidade:"KG", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Manteiga", categoria:"OUTROS", unidade:"KG", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Etiqueta", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Folha de ofício", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Piloto para quadro branco", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Shoyu sachê", categoria:"DEPOSITO", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Berço para shoyu", categoria:"DEPOSITO", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Shimeji", categoria:"DEPOSITO", unidade:"PLACAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Alho descascado", categoria:"DEPOSITO", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Pote para balls", categoria:"DEPOSITO", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Pote para molho", categoria:"DEPOSITO", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Lacre Poke", categoria:"DEPOSITO", unidade:"ROLO", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Lacre Ykedin", categoria:"DEPOSITO", unidade:"ROLO", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sacola craft Ykedin", categoria:"DEPOSITO", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sacola craft Poke", categoria:"DEPOSITO", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Batata palito", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Peito de frango", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Tonkatsu", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Panko", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Camarão com casca", categoria:"DEPOSITO", unidade:"KG", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Macarrão Ykedin", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Óleo de algodão", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Óleo de gergelim", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  // ATENDIMENTO
  { nome:"Limão taiti", categoria:"FEIRA", unidade:"KG", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Abacaxi", categoria:"FEIRA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Maracujá", categoria:"FEIRA", unidade:"KG", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Uva verde", categoria:"FEIRA", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Morango fresco (atendimento)", categoria:"FEIRA", unidade:"PLACAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Hortelã", categoria:"VERDURÃO", unidade:"PÉS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Canela lasca", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Albumina", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Anis estrelado", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Bucha", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Água sanitária", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sabão em pó", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Detergente", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Chocolate para café cliente", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Cápsula de café", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Colher de sobremesa descartável", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Prato de sobremesa descartável", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Copo descartável", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Canudo de suco", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Canudo de drink", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sacola para refri 50x50", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sachê de açúcar", categoria:"VÂNIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sachê de sal", categoria:"VÂNIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sachê de adoçante", categoria:"VÂNIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Palito empacotado", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Colher para café", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Papel higiênico", categoria:"CLORO E CIA", unidade:"ROLOS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Saco de lixo 200L", categoria:"CLORO E CIA", unidade:"FARDO", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Saco de lixo 15L", categoria:"CLORO E CIA", unidade:"FARDO", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Álcool em gel", categoria:"CLORO E CIA", unidade:"LITROS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Álcool líquido", categoria:"CLORO E CIA", unidade:"LITROS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Multiuso perfumado", categoria:"CLORO E CIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Papel toalha p/ banheiro", categoria:"CLORO E CIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sabonete líquido", categoria:"CLORO E CIA", unidade:"LITROS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Guardanapo mesa", categoria:"CLORO E CIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Inseticida", categoria:"CLORO E CIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Água sem gás", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Água com gás", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Coca pet 1L", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Coca cola LS 1L", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Coca zero pet 1L", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Coca lata", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Coca zero lata", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Fanta laranja lata", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Kuat lata", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sprite lata", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Schweppes citrus", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Schweppes tônica", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Energético Monster", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Del valle uva", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sprite lemon fresh", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Amstel 600ml", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Heineken 600ml", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Heineken long neck", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Heineken zero long neck", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sakê garrafa", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Rum", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Aperol", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Whiskey Old Parr 12 anos", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Whiskey Ballantines 8 anos", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Vodca Smirnoff", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Gin", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Cachaça", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Curaçau blue", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Espumante demi sec", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Espumante moscatel", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Espumante brut rosé", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Hashi", categoria:"OUTROS", unidade:"PCT", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Espuma de gengibre", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Bobina de impressora", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Caneta", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Marca texto", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Grampo", categoria:"OUTROS", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Piloto", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Bobina de máquina de cartão", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Embalagem de talher", categoria:"OUTROS", unidade:"PCT", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Adaptador de hashi", categoria:"OUTROS", unidade:"PCT", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Wasabi", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Gengibre em conserva", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Amora congelada", categoria:"OUTROS", unidade:"PCT", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Framboesa congelada", categoria:"OUTROS", unidade:"PCT", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Morango congelado", categoria:"OUTROS", unidade:"PCT", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Porções de frutas vermelhas", categoria:"OUTROS", unidade:"PORÇÃO", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Porções de morango", categoria:"OUTROS", unidade:"PORÇÃO", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Porções de maracujá", categoria:"OUTROS", unidade:"PORÇÃO", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Porções de abacaxi", categoria:"OUTROS", unidade:"PORÇÃO", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Abacaxi sem porcionar", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Maracujá sem porcionar", categoria:"OUTROS", unidade:"KG", meta:1, restaurante:"Ykedin Jacobina" },
  // SUSHIBAR
  { nome:"Acelga", categoria:"FEIRA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Chuchu", categoria:"FEIRA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Pepino japonês", categoria:"FEIRA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Manga", categoria:"FEIRA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Maçã verde", categoria:"FEIRA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Cebola roxa", categoria:"VERDURÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Couve pés", categoria:"VERDURÃO", unidade:"PÉS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Couve sacos", categoria:"VERDURÃO", unidade:"SACOS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Salsa", categoria:"VERDURÃO", unidade:"PÉS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Manjericão", categoria:"VERDURÃO", unidade:"PÉS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Cebolinha", categoria:"VERDURÃO", unidade:"PÉS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Chips de banana", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Chips de batata", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Chips de mandioca", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Mix de castanha", categoria:"DR SHAPE", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Gengibre", categoria:"MERCADO", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Azeite", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Pimenta de cheiro", categoria:"MERCADO", unidade:"GRAMAS", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Goiabada em barra", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Queijo mussarela da região", categoria:"OUTROS", unidade:"BARRA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Folha de ouro", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Embalagem de temaki", categoria:"DEPOSITO", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Embalagem de ceviche", categoria:"DEPOSITO", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Caixa n1", categoria:"DEPOSITO", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Caixa n2", categoria:"DEPOSITO", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Caixa n3", categoria:"DEPOSITO", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Caixa n4", categoria:"DEPOSITO", unidade:"PACOTE", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Embalagem de poke", categoria:"DEPOSITO", unidade:"CAIXA", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Barca plástica M", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Barca plástica G", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Sakê culinário", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Vinagre de arroz 20L", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Shoyu 20L", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Gás para maçarico", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Pimenta biquinho", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Geleia de pimenta biquinho", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Cream cheese balde", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Salmão", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Camarão sem casca", categoria:"DEPOSITO", unidade:"KG", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Kani", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Peixe branco", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Massa de harumaki", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Nori", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Arroz japonês", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Pimenta sriracha", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Ovas de massago", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Gergelim preto", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Gergelim branco", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Hondashi", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Rolo de perfex", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Glutamato", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
  { nome:"Doritos", categoria:"DEPOSITO", unidade:"UNI", meta:1, restaurante:"Ykedin Jacobina" },
];

export const CG: ProdutoSeed[] = [
  // COZINHA
  { nome:"Laranja", categoria:"FEIRA", unidade:"KG", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Repolho branco", categoria:"FEIRA", unidade:"UNI", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Repolho roxo", categoria:"FEIRA", unidade:"UNI", meta:15, restaurante:"Ykedin Capim Grosso" },
  { nome:"Cenoura", categoria:"FEIRA", unidade:"KG", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Banana da terra", categoria:"FEIRA", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Cebola branca", categoria:"FEIRA", unidade:"KG", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Tomate maduros e firmes", categoria:"FEIRA", unidade:"UNI", meta:40, restaurante:"Ykedin Capim Grosso" },
  { nome:"Batatinha", categoria:"FEIRA", unidade:"UNI", meta:30, restaurante:"Ykedin Capim Grosso" },
  { nome:"Brócolis", categoria:"FEIRA", unidade:"UNI", meta:6, restaurante:"Ykedin Capim Grosso" },
  { nome:"Morango fresco", categoria:"FEIRA", unidade:"KG", meta:5, restaurante:"Ykedin Capim Grosso" },
  { nome:"Coentro", categoria:"VERDURÃO", unidade:"PÉS", meta:3, restaurante:"Ykedin Capim Grosso" },
  { nome:"Pimentão vermelho", categoria:"VERDURÃO", unidade:"UNI", meta:6, restaurante:"Ykedin Capim Grosso" },
  { nome:"Pimentão verde", categoria:"VERDURÃO", unidade:"UNI", meta:8, restaurante:"Ykedin Capim Grosso" },
  { nome:"Alface", categoria:"VERDURÃO", unidade:"PÉS", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Castanha", categoria:"DR SHAPE", unidade:"GRAMAS", meta:300, restaurante:"Ykedin Capim Grosso" },
  { nome:"Castanha triturada", categoria:"DR SHAPE", unidade:"GRAMAS", meta:300, restaurante:"Ykedin Capim Grosso" },
  { nome:"Cominho", categoria:"DR SHAPE", unidade:"GRAMAS", meta:300, restaurante:"Ykedin Capim Grosso" },
  { nome:"Orégano", categoria:"DR SHAPE", unidade:"GRAMAS", meta:300, restaurante:"Ykedin Capim Grosso" },
  { nome:"Pimenta do reino", categoria:"DR SHAPE", unidade:"GRAMAS", meta:300, restaurante:"Ykedin Capim Grosso" },
  { nome:"Canela em pó", categoria:"DR SHAPE", unidade:"GRAMAS", meta:300, restaurante:"Ykedin Capim Grosso" },
  { nome:"Lemon pepper", categoria:"DR SHAPE", unidade:"GRAMAS", meta:200, restaurante:"Ykedin Capim Grosso" },
  { nome:"Corante", categoria:"DR SHAPE", unidade:"GRAMAS", meta:300, restaurante:"Ykedin Capim Grosso" },
  { nome:"Açúcar", categoria:"ATACADÃO", unidade:"UNI", meta:20, restaurante:"Ykedin Capim Grosso" },
  { nome:"Óleo", categoria:"ATACADÃO", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Farinha de trigo", categoria:"ATACADÃO", unidade:"UNI", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Arroz", categoria:"ATACADÃO", unidade:"UNI", meta:8, restaurante:"Ykedin Capim Grosso" },
  { nome:"Papel toalha", categoria:"ATACADÃO", unidade:"UNI", meta:24, restaurante:"Ykedin Capim Grosso" },
  { nome:"Bombril", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Leite", categoria:"ATACADÃO", unidade:"UNI", meta:15, restaurante:"Ykedin Capim Grosso" },
  { nome:"Presunto", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Extrato elefante", categoria:"MERCADO", unidade:"UNI", meta:4, restaurante:"Ykedin Capim Grosso" },
  { nome:"Maionese", categoria:"MERCADO", unidade:"UNI", meta:4, restaurante:"Ykedin Capim Grosso" },
  { nome:"Café", categoria:"MERCADO", unidade:"UNI", meta:6, restaurante:"Ykedin Capim Grosso" },
  { nome:"Macarrão ninho", categoria:"MERCADO", unidade:"UNI", meta:3, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sorvete", categoria:"MERCADO", unidade:"UNI", meta:8, restaurante:"Ykedin Capim Grosso" },
  { nome:"Ovos", categoria:"MERCADO", unidade:"PLACAS", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Veja", categoria:"MERCADO", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Vinagre", categoria:"MERCADO", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Isqueiro", categoria:"MERCADO", unidade:"UNI", meta:4, restaurante:"Ykedin Capim Grosso" },
  { nome:"Feijão", categoria:"MERCADO", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Caldo de legumes", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Nescal", categoria:"MERCADO", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sal", categoria:"MERCADO", unidade:"UNI", meta:4, restaurante:"Ykedin Capim Grosso" },
  { nome:"Caldo de galinha Knorr", categoria:"MERCADO", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Fermento químico", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Embalagem rolinho", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Saco de congelamento 1kg", categoria:"VÂNIA", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Saco de congelamento 5kg", categoria:"VÂNIA", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Calda de chocolate para sorvete", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Plástico filme grande", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Cereja", categoria:"VÂNIA", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Bicarbonato de sódio", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Toucas", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Luva P", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Luvas M", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Luvas G", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Luvas GG", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Doce de leite", categoria:"VÂNIA", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Corante vermelho bordô em pó", categoria:"VÂNIA", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Chocolate em barra", categoria:"VÂNIA", unidade:"UNI", meta:4, restaurante:"Ykedin Capim Grosso" },
  { nome:"Amido de milho", categoria:"VÂNIA", unidade:"UNI", meta:6, restaurante:"Ykedin Capim Grosso" },
  { nome:"Essência de baunilha", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Chocolate 70%", categoria:"VÂNIA", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Papel manteiga", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Saco de confeiteiro", categoria:"VÂNIA", unidade:"UNI", meta:5, restaurante:"Ykedin Capim Grosso" },
  { nome:"Açúcar refinado", categoria:"VÂNIA", unidade:"UNI", meta:5, restaurante:"Ykedin Capim Grosso" },
  { nome:"Catchup", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Garfo descartável reforçado", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Faca descartável reforçado", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Pote de 530ml com tampa", categoria:"VÂNIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Caneta em gel", categoria:"VÂNIA", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Desengordurante", categoria:"CLORO E CIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Desincrustante", categoria:"CLORO E CIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Fibraço", categoria:"CLORO E CIA", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Carne", categoria:"PEDRO", unidade:"KG", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Manteiga", categoria:"PEDRO", unidade:"KG", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Queijo mussarela da região", categoria:"PEDRO", unidade:"BARRA", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Macarrão Ykedin", categoria:"PEDRO", unidade:"UNI", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Shoyu sachê", categoria:"PEDRO", unidade:"CAIXA", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Berço para shoyu", categoria:"PEDRO", unidade:"CAIXA", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Tonkatsu", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Panko", categoria:"PEDRO", unidade:"UNI", meta:6, restaurante:"Ykedin Capim Grosso" },
  { nome:"Alho descascado", categoria:"PEDRO", unidade:"UNI", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Óleo de algodão", categoria:"PEDRO", unidade:"UNI", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Óleo de gergelim", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Shimeji", categoria:"PEDRO", unidade:"PLACAS", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Batata palito", categoria:"DINE", unidade:"UNI", meta:5, restaurante:"Ykedin Capim Grosso" },
  { nome:"Peito de frango", categoria:"DINE", unidade:"KG", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Camarão com casca", categoria:"LUIZ", unidade:"KG", meta:5, restaurante:"Ykedin Capim Grosso" },
  { nome:"Pote para balls", categoria:"LUIZ", unidade:"PACOTE", meta:4, restaurante:"Ykedin Capim Grosso" },
  { nome:"Lacre Ykedin", categoria:"LUIZ", unidade:"ROLO", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sacola craft Ykedin", categoria:"LUIZ", unidade:"PACOTE", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sacola craft poke", categoria:"LUIZ", unidade:"PACOTE", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Lacre Poke", categoria:"LUIZ", unidade:"ROLO", meta:1, restaurante:"Ykedin Capim Grosso" },
  // ATENDIMENTO
  { nome:"Limão taiti", categoria:"FEIRA", unidade:"KG", meta:15, restaurante:"Ykedin Capim Grosso" },
  { nome:"Abacaxi", categoria:"FEIRA", unidade:"UNI", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Maracujá", categoria:"FEIRA", unidade:"KG", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Uva verde", categoria:"FEIRA", unidade:"GRAMAS", meta:1000, restaurante:"Ykedin Capim Grosso" },
  { nome:"Morango fresco (atendimento)", categoria:"FEIRA", unidade:"PLACAS", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Hortelã", categoria:"VERDURÃO", unidade:"PÉS", meta:3, restaurante:"Ykedin Capim Grosso" },
  { nome:"Canela lasca", categoria:"DR SHAPE", unidade:"GRAMAS", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Albumina", categoria:"DR SHAPE", unidade:"GRAMAS", meta:100, restaurante:"Ykedin Capim Grosso" },
  { nome:"Anis estrelado", categoria:"DR SHAPE", unidade:"GRAMAS", meta:200, restaurante:"Ykedin Capim Grosso" },
  { nome:"Bucha", categoria:"ATACADÃO", unidade:"UNI", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Água sanitária", categoria:"ATACADÃO", unidade:"UNI", meta:30, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sabão em pó", categoria:"ATACADÃO", unidade:"UNI", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Detergente", categoria:"ATACADÃO", unidade:"UNI", meta:20, restaurante:"Ykedin Capim Grosso" },
  { nome:"Chocolate para café cliente", categoria:"MERCADO", unidade:"UNI", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Cápsula de café", categoria:"MERCADO", unidade:"UNI", meta:15, restaurante:"Ykedin Capim Grosso" },
  { nome:"Colher de sobremesa descartável reforçado", categoria:"VÂNIA", unidade:"PACOTE", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Prato de sobremesa descartável", categoria:"VÂNIA", unidade:"PACOTE", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Copo descartável", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Canudo de suco", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Canudo de drink", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sacola para refri 50x50", categoria:"VÂNIA", unidade:"PACOTE", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sachê de açúcar", categoria:"VÂNIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sachê de sal", categoria:"VÂNIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sachê de adoçante", categoria:"VÂNIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Palito empacotado", categoria:"VÂNIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Colher para café", categoria:"VÂNIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Papel higiênico", categoria:"CLORO E CIA", unidade:"ROLOS", meta:4, restaurante:"Ykedin Capim Grosso" },
  { nome:"Saco de lixo 200L", categoria:"CLORO E CIA", unidade:"FARDO", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Saco de lixo 15L", categoria:"CLORO E CIA", unidade:"FARDO", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Álcool em gel", categoria:"CLORO E CIA", unidade:"LITROS", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Álcool líquido", categoria:"CLORO E CIA", unidade:"LITROS", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Multiuso perfumado", categoria:"CLORO E CIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Papel toalha p/ banheiro", categoria:"CLORO E CIA", unidade:"PACOTE", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sabonete líquido", categoria:"CLORO E CIA", unidade:"LITROS", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Guardanapo mesa", categoria:"CLORO E CIA", unidade:"CAIXA", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Inseticida", categoria:"CLORO E CIA", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Água sem gás", categoria:"BEBIDAS", unidade:"UNI", meta:36, restaurante:"Ykedin Capim Grosso" },
  { nome:"Água com gás", categoria:"BEBIDAS", unidade:"UNI", meta:36, restaurante:"Ykedin Capim Grosso" },
  { nome:"Coca pet 1L", categoria:"BEBIDAS", unidade:"UNI", meta:24, restaurante:"Ykedin Capim Grosso" },
  { nome:"Coca cola LS 1L", categoria:"BEBIDAS", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Coca zero pet 1L", categoria:"BEBIDAS", unidade:"UNI", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Coca lata", categoria:"BEBIDAS", unidade:"UNI", meta:24, restaurante:"Ykedin Capim Grosso" },
  { nome:"Coca zero lata", categoria:"BEBIDAS", unidade:"UNI", meta:24, restaurante:"Ykedin Capim Grosso" },
  { nome:"Fanta laranja lata", categoria:"BEBIDAS", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Kuat lata", categoria:"BEBIDAS", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sprite lata", categoria:"BEBIDAS", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Schweppes citrus", categoria:"BEBIDAS", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Schweppes tônica", categoria:"BEBIDAS", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Energético Monster", categoria:"BEBIDAS", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Del valle uva", categoria:"BEBIDAS", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sprite lemon fresh", categoria:"BEBIDAS", unidade:"UNI", meta:24, restaurante:"Ykedin Capim Grosso" },
  { nome:"Amstel 600ml", categoria:"BEBIDAS", unidade:"UNI", meta:50, restaurante:"Ykedin Capim Grosso" },
  { nome:"Heineken 600ml", categoria:"BEBIDAS", unidade:"UNI", meta:50, restaurante:"Ykedin Capim Grosso" },
  { nome:"Heineken long neck", categoria:"BEBIDAS", unidade:"UNI", meta:24, restaurante:"Ykedin Capim Grosso" },
  { nome:"Heineken zero long neck", categoria:"BEBIDAS", unidade:"UNI", meta:24, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sakê garrafa", categoria:"BEBIDAS", unidade:"UNI", meta:3, restaurante:"Ykedin Capim Grosso" },
  { nome:"Rum", categoria:"BEBIDAS", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Aperol", categoria:"BEBIDAS", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Whiskey Old Parr 12 anos", categoria:"BEBIDAS", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Whiskey Ballantines 8 anos", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Vodca Smirnoff", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Gin", categoria:"BEBIDAS", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Cachaça", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Curaçau blue", categoria:"BEBIDAS", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Espumante demi sec", categoria:"BEBIDAS", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Espumante moscatel", categoria:"BEBIDAS", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Espumante brut rosé", categoria:"BEBIDAS", unidade:"UNI", meta:12, restaurante:"Ykedin Capim Grosso" },
  { nome:"Hashi", categoria:"OUTROS", unidade:"PCT", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Embalagem de talher (pct com 100)", categoria:"OUTROS", unidade:"PCT", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Espuma de gengibre", categoria:"OUTROS", unidade:"UNI", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Amora congelada", categoria:"OUTROS", unidade:"PCT", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Framboesa congelada", categoria:"OUTROS", unidade:"PCT", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Morango congelado", categoria:"OUTROS", unidade:"PCT", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Porções de frutas vermelhas", categoria:"OUTROS", unidade:"PORÇÃO", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Porções de morango", categoria:"OUTROS", unidade:"PORÇÃO", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Adaptador de hashi", categoria:"PEDRO", unidade:"PCT", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Wasabi", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Gengibre em conserva", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  // SUSHIBAR
  { nome:"Acelga", categoria:"FEIRA", unidade:"UNI", meta:4, restaurante:"Ykedin Capim Grosso" },
  { nome:"Chuchu", categoria:"FEIRA", unidade:"UNI", meta:20, restaurante:"Ykedin Capim Grosso" },
  { nome:"Pepino japonês", categoria:"FEIRA", unidade:"UNI", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Manga", categoria:"FEIRA", unidade:"UNI", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Maçã verde", categoria:"FEIRA", unidade:"UNI", meta:15, restaurante:"Ykedin Capim Grosso" },
  { nome:"Cebola roxa", categoria:"VERDURÃO", unidade:"UNI", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Couve pés", categoria:"VERDURÃO", unidade:"PÉS", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Couve sacos", categoria:"VERDURÃO", unidade:"SACOS", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Salsa", categoria:"VERDURÃO", unidade:"PÉS", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Manjericão", categoria:"VERDURÃO", unidade:"PÉS", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Cebolinha", categoria:"VERDURÃO", unidade:"PÉS", meta:15, restaurante:"Ykedin Capim Grosso" },
  { nome:"Chips de banana", categoria:"DR SHAPE", unidade:"GRAMAS", meta:300, restaurante:"Ykedin Capim Grosso" },
  { nome:"Chips de batata", categoria:"DR SHAPE", unidade:"GRAMAS", meta:300, restaurante:"Ykedin Capim Grosso" },
  { nome:"Chips de mandioca", categoria:"DR SHAPE", unidade:"GRAMAS", meta:300, restaurante:"Ykedin Capim Grosso" },
  { nome:"Mix de castanha", categoria:"DR SHAPE", unidade:"GRAMAS", meta:300, restaurante:"Ykedin Capim Grosso" },
  { nome:"Gengibre", categoria:"MERCADO", unidade:"GRAMAS", meta:300, restaurante:"Ykedin Capim Grosso" },
  { nome:"Azeite", categoria:"MERCADO", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Pimenta de cheiro", categoria:"MERCADO", unidade:"GRAMAS", meta:200, restaurante:"Ykedin Capim Grosso" },
  { nome:"Goiabada em barra", categoria:"VÂNIA", unidade:"UNI", meta:3, restaurante:"Ykedin Capim Grosso" },
  { nome:"Folha de ouro", categoria:"OUTROS", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Queijo mussarela da região (sushibar)", categoria:"PEDRO", unidade:"BARRA", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Arroz japonês", categoria:"PEDRO", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Massa de harumaki", categoria:"PEDRO", unidade:"UNI", meta:10, restaurante:"Ykedin Capim Grosso" },
  { nome:"Nori", categoria:"PEDRO", unidade:"UNI", meta:6, restaurante:"Ykedin Capim Grosso" },
  { nome:"Pimenta sriracha", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Gergelim preto", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Gergelim branco", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Hondashi", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Rolo de perfex", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Glutamato", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Sakê culinário", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Vinagre de arroz 20L", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Shoyu 20L", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Gás para maçarico", categoria:"PEDRO", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Pimenta biquinho", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Geleia de pimenta biquinho", categoria:"PEDRO", unidade:"UNI", meta:1, restaurante:"Ykedin Capim Grosso" },
  { nome:"Cream cheese", categoria:"PEDRO", unidade:"UNI", meta:7, restaurante:"Ykedin Capim Grosso" },
  { nome:"Barca plástica M", categoria:"PEDRO", unidade:"UNI", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Barca plástica G", categoria:"PEDRO", unidade:"UNI", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Embalagem de poke", categoria:"PEDRO", unidade:"CAIXA", meta:0, restaurante:"Ykedin Capim Grosso" },
  { nome:"Doritos", categoria:"DINE", unidade:"UNI", meta:5, restaurante:"Ykedin Capim Grosso" },
  { nome:"Camarão sem casca", categoria:"LUIZ", unidade:"KG", meta:15, restaurante:"Ykedin Capim Grosso" },
  { nome:"Salmão", categoria:"LUIZ", unidade:"UNI", meta:17, restaurante:"Ykedin Capim Grosso" },
  { nome:"Kani", categoria:"LUIZ", unidade:"UNI", meta:7, restaurante:"Ykedin Capim Grosso" },
  { nome:"Ovas de massago", categoria:"LUIZ", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Peixe branco", categoria:"LUIZ", unidade:"UNI", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Embalagem de temaki", categoria:"LUIZ", unidade:"PACOTE", meta:3, restaurante:"Ykedin Capim Grosso" },
  { nome:"Embalagem de ceviche", categoria:"LUIZ", unidade:"PACOTE", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Caixa n1", categoria:"LUIZ", unidade:"PACOTE", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Caixa n2", categoria:"LUIZ", unidade:"PACOTE", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Caixa n3", categoria:"LUIZ", unidade:"PACOTE", meta:2, restaurante:"Ykedin Capim Grosso" },
  { nome:"Caixa n4", categoria:"LUIZ", unidade:"PACOTE", meta:2, restaurante:"Ykedin Capim Grosso" },
];

export const DECK: ProdutoSeed[] = [
  { nome:"Laranja", categoria:"FEIRA", unidade:"KG", meta:1, restaurante:"Deck" },
  { nome:"Limão Taiti", categoria:"FEIRA", unidade:"KG", meta:1, restaurante:"Deck" },
  { nome:"Cebola Branca", categoria:"FEIRA", unidade:"KG", meta:1, restaurante:"Deck" },
  { nome:"Tomate", categoria:"FEIRA", unidade:"KG", meta:1, restaurante:"Deck" },
  { nome:"Cenoura", categoria:"VERDURÃO", unidade:"KG", meta:1, restaurante:"Deck" },
  { nome:"Alface", categoria:"VERDURÃO", unidade:"UNI", meta:1, restaurante:"Deck" },
  { nome:"Sal", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Deck" },
  { nome:"Óleo", categoria:"MERCADO", unidade:"UNI", meta:1, restaurante:"Deck" },
  { nome:"Arroz", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Deck" },
  { nome:"Açúcar", categoria:"ATACADÃO", unidade:"UNI", meta:1, restaurante:"Deck" },
];

type DB = {
  $queryRawUnsafe<T = unknown>(query: string, ...values: unknown[]): Promise<T>;
  $executeRawUnsafe(query: string, ...values: unknown[]): Promise<number>;
};

export async function seedProdutos(db: DB) {
  const counts = await db.$queryRawUnsafe<{ restaurante: string | null; total: unknown }[]>(
    `SELECT restaurante, COUNT(*) as total FROM "ProdutoEstoque" WHERE ativo=1 GROUP BY restaurante`,
  );
  const existing = Object.fromEntries(counts.map((r) => [r.restaurante ?? "", Number(r.total)]));

  const toInsert: ProdutoSeed[] = [];
  if (!existing["Ykedin Jacobina"]) toInsert.push(...JACOBINA);
  if (!existing["Ykedin Capim Grosso"]) toInsert.push(...CG);
  if (!existing["Deck"]) toInsert.push(...DECK);

  for (const p of toInsert) {
    const id = randomUUID();
    await db.$executeRawUnsafe(
      `INSERT OR IGNORE INTO "ProdutoEstoque"
         ("id","nome","categoria","unidade","quantidadeAtual","quantidadeMinima",
          "metaSemanal","qtdPorPacote","ilimitado","sacaThresholdCheia","sacaThresholdMeia",
          "restaurante","ordemCategoria")
       VALUES (?,?,?,?,0,0,?,1,0,null,null,?,?)`,
      id, p.nome, p.categoria, p.unidade, p.meta, p.restaurante,
      CAT_ORDER[p.categoria] ?? 99,
    );
  }

  return toInsert.length;
}
