import { randomUUID } from "crypto";

const CAT_ORDER: Record<string, number> = {
  "FEIRA": 1, "VERDURÃO": 2, "DR SHAPE": 3, "ATACADÃO": 4, "MERCADO": 5,
  "VÂNIA": 6, "CLORO E CIA": 7, "BEBIDAS": 8, "OUTROS": 9, "DEPOSITO": 10,
  "PEDRO": 11, "DINE": 12, "LUIZ": 13, "SERTÃO NATURAL": 14, "ESTOQUE DE INSUMOS": 15,
};

export type ProdutoSeed = {
  nome: string; categoria: string; unidade: string;
  meta: number; restaurante: string; setor: string;
};

type Item = { nome: string; categoria: string; unidade: string; meta: number };

function b(restaurante: string, setor: string, itens: Item[]): ProdutoSeed[] {
  return itens.map((p) => ({ ...p, restaurante, setor }));
}

const j = "Ykedin Jacobina";
const cg = "Ykedin Capim Grosso";
const dk = "Deck";

// ─── Ykedin Jacobina ──────────────────────────────────────────────────────────

export const JACOBINA: ProdutoSeed[] = [
  ...b(j, "Cozinha", [
    // FEIRA
    { nome:"Laranja",                   categoria:"FEIRA",       unidade:"KG",     meta:1 },
    { nome:"Repolho branco",            categoria:"FEIRA",       unidade:"UNI",    meta:1 },
    { nome:"Repolho roxo",              categoria:"FEIRA",       unidade:"UNI",    meta:1 },
    { nome:"Cenoura",                   categoria:"FEIRA",       unidade:"KG",     meta:1 },
    { nome:"Banana da terra",           categoria:"FEIRA",       unidade:"UNI",    meta:1 },
    { nome:"Cebola branca",             categoria:"FEIRA",       unidade:"KG",     meta:1 },
    { nome:"Tomate maduros e firmes",   categoria:"FEIRA",       unidade:"UNI",    meta:1 },
    { nome:"Batatinha",                 categoria:"FEIRA",       unidade:"UNI",    meta:1 },
    { nome:"Brócolis",                  categoria:"FEIRA",       unidade:"UNI",    meta:1 },
    { nome:"Morango fresco",            categoria:"FEIRA",       unidade:"KG",     meta:1 },
    // VERDURÃO
    { nome:"Coentro",                   categoria:"VERDURÃO",    unidade:"PÉS",    meta:1 },
    { nome:"Pimentão vermelho",         categoria:"VERDURÃO",    unidade:"UNI",    meta:1 },
    { nome:"Pimentão verde",            categoria:"VERDURÃO",    unidade:"UNI",    meta:1 },
    { nome:"Alface",                    categoria:"VERDURÃO",    unidade:"PÉS",    meta:1 },
    // DR SHAPE
    { nome:"Castanha",                  categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    { nome:"Castanha triturada",        categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    { nome:"Cominho",                   categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    { nome:"Orégano",                   categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    { nome:"Pimenta do reino",          categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    { nome:"Canela em pó",              categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    { nome:"Lemon pepper",              categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    { nome:"Corante",                   categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    // ATACADÃO
    { nome:"Açúcar",                    categoria:"ATACADÃO",    unidade:"UNI",    meta:1 },
    { nome:"Óleo",                      categoria:"ATACADÃO",    unidade:"UNI",    meta:1 },
    { nome:"Farinha de trigo",          categoria:"ATACADÃO",    unidade:"UNI",    meta:1 },
    { nome:"Arroz",                     categoria:"ATACADÃO",    unidade:"UNI",    meta:1 },
    { nome:"Papel toalha",              categoria:"ATACADÃO",    unidade:"UNI",    meta:1 },
    { nome:"Bombril",                   categoria:"ATACADÃO",    unidade:"UNI",    meta:1 },
    { nome:"Leite",                     categoria:"ATACADÃO",    unidade:"UNI",    meta:1 },
    // MERCADO
    { nome:"Presunto",                  categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Extrato elefante",          categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Maionese",                  categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Café",                      categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Macarrão ninho",            categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Sorvete",                   categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Ovos",                      categoria:"MERCADO",     unidade:"PLACAS", meta:1 },
    { nome:"Veja",                      categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Vinagre",                   categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Isqueiro",                  categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Feijão",                    categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Caldo de legumes",          categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Nescal",                    categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Sal",                       categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Caldo de galinha Knorr",    categoria:"MERCADO",     unidade:"TABLETS",meta:1 },
    { nome:"Fermento químico",          categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    // VÂNIA
    { nome:"Embalagem rolinho",         categoria:"VÂNIA",       unidade:"CAIXA",  meta:1 },
    { nome:"Saco de congelamento 1kg",  categoria:"VÂNIA",       unidade:"BOBINA", meta:1 },
    { nome:"Saco de congelamento 5kg",  categoria:"VÂNIA",       unidade:"BOBINA", meta:1 },
    { nome:"Calda de chocolate para sorvete", categoria:"VÂNIA", unidade:"UNI",    meta:1 },
    { nome:"Plástico filme grande",     categoria:"VÂNIA",       unidade:"BOBINA", meta:1 },
    { nome:"Cereja",                    categoria:"VÂNIA",       unidade:"UNI",    meta:1 },
    { nome:"Bicarbonato de sódio",      categoria:"VÂNIA",       unidade:"UNI",    meta:1 },
    { nome:"Toucas",                    categoria:"VÂNIA",       unidade:"CAIXA",  meta:1 },
    { nome:"Luva P",                    categoria:"VÂNIA",       unidade:"CAIXA",  meta:1 },
    { nome:"Luvas M",                   categoria:"VÂNIA",       unidade:"CAIXA",  meta:1 },
    { nome:"Luvas G",                   categoria:"VÂNIA",       unidade:"CAIXA",  meta:1 },
    { nome:"Luvas GG",                  categoria:"VÂNIA",       unidade:"CAIXA",  meta:1 },
    { nome:"Doce de leite",             categoria:"VÂNIA",       unidade:"UNI",    meta:1 },
    { nome:"Corante vermelho bordô em pó", categoria:"VÂNIA",    unidade:"UNI",    meta:1 },
    { nome:"Chocolate em barra",        categoria:"VÂNIA",       unidade:"BARRA",  meta:1 },
    { nome:"Chocolate ao leite em barra", categoria:"VÂNIA",     unidade:"BARRA",  meta:1 },
    { nome:"Amido de milho",            categoria:"VÂNIA",       unidade:"KG",     meta:1 },
    { nome:"Essência de baunilha",      categoria:"VÂNIA",       unidade:"UNI",    meta:1 },
    { nome:"Chocolate 70%",             categoria:"VÂNIA",       unidade:"BARRA",  meta:1 },
    { nome:"Papel manteiga",            categoria:"VÂNIA",       unidade:"ROLO",   meta:1 },
    { nome:"Saco de confeiteiro",       categoria:"VÂNIA",       unidade:"UNI",    meta:1 },
    { nome:"Açúcar refinado",           categoria:"VÂNIA",       unidade:"UNI",    meta:1 },
    { nome:"Catchup",                   categoria:"VÂNIA",       unidade:"UNI",    meta:1 },
    { nome:"Garfo descartável reforçado", categoria:"VÂNIA",     unidade:"PACOTE", meta:1 },
    { nome:"Faca descartável reforçada",  categoria:"VÂNIA",     unidade:"PACOTE", meta:1 },
    { nome:"Pote de 530ml com tampa",   categoria:"VÂNIA",       unidade:"PACOTE", meta:1 },
    { nome:"Caneta em gel",             categoria:"VÂNIA",       unidade:"UNI",    meta:1 },
    // CLORO E CIA
    { nome:"Desengordurante",           categoria:"CLORO E CIA", unidade:"UNI",    meta:1 },
    { nome:"Desincrustante",            categoria:"CLORO E CIA", unidade:"UNI",    meta:1 },
    { nome:"Vela de aniversário",       categoria:"CLORO E CIA", unidade:"UNI",    meta:1 },
    { nome:"Fibraço",                   categoria:"CLORO E CIA", unidade:"UNI",    meta:1 },
    // OUTROS
    { nome:"Queijo",                    categoria:"OUTROS",      unidade:"BARRA",  meta:1 },
    { nome:"Carne",                     categoria:"OUTROS",      unidade:"KG",     meta:1 },
    { nome:"Manteiga",                  categoria:"OUTROS",      unidade:"KG",     meta:1 },
    { nome:"Etiqueta",                  categoria:"OUTROS",      unidade:"UNI",    meta:1 },
    { nome:"Folha de ofício",           categoria:"OUTROS",      unidade:"UNI",    meta:1 },
    { nome:"Piloto para quadro branco", categoria:"OUTROS",      unidade:"UNI",    meta:1 },
    // DEPOSITO
    { nome:"Shoyu sachê",               categoria:"DEPOSITO",    unidade:"CAIXA",  meta:1 },
    { nome:"Berço para shoyu",          categoria:"DEPOSITO",    unidade:"CAIXA",  meta:1 },
    { nome:"Shimeji",                   categoria:"DEPOSITO",    unidade:"PLACAS", meta:1 },
    { nome:"Alho descascado",           categoria:"DEPOSITO",    unidade:"PACOTE", meta:1 },
    { nome:"Pote para balls",           categoria:"DEPOSITO",    unidade:"PACOTE", meta:1 },
    { nome:"Pote para molho",           categoria:"DEPOSITO",    unidade:"CAIXA",  meta:1 },
    { nome:"Lacre Poke",                categoria:"DEPOSITO",    unidade:"ROLO",   meta:1 },
    { nome:"Lacre Ykedin",              categoria:"DEPOSITO",    unidade:"ROLO",   meta:1 },
    { nome:"Sacola craft Ykedin",       categoria:"DEPOSITO",    unidade:"PACOTE", meta:1 },
    { nome:"Sacola craft Poke",         categoria:"DEPOSITO",    unidade:"PACOTE", meta:1 },
    { nome:"Batata palito",             categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Peito de frango",           categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Tonkatsu",                  categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Panko",                     categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Camarão com casca",         categoria:"DEPOSITO",    unidade:"KG",     meta:1 },
    { nome:"Macarrão Ykedin",           categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Óleo de algodão",           categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Óleo de gergelim",          categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
  ]),

  ...b(j, "Atendimento", [
    // FEIRA
    { nome:"Limão taiti",               categoria:"FEIRA",       unidade:"KG",     meta:1 },
    { nome:"Abacaxi",                   categoria:"FEIRA",       unidade:"UNI",    meta:1 },
    { nome:"Maracujá",                  categoria:"FEIRA",       unidade:"KG",     meta:1 },
    { nome:"Uva verde",                 categoria:"FEIRA",       unidade:"GRAMAS", meta:1 },
    { nome:"Morango fresco atend.",     categoria:"FEIRA",       unidade:"PLACAS", meta:1 },
    // VERDURÃO
    { nome:"Hortelã",                   categoria:"VERDURÃO",    unidade:"PÉS",    meta:1 },
    // DR SHAPE
    { nome:"Canela lasca",              categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    { nome:"Albumina",                  categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    { nome:"Anis estrelado",            categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    // ATACADÃO
    { nome:"Bucha",                     categoria:"ATACADÃO",    unidade:"UNI",    meta:1 },
    { nome:"Água sanitária",            categoria:"ATACADÃO",    unidade:"UNI",    meta:1 },
    { nome:"Sabão em pó",               categoria:"ATACADÃO",    unidade:"UNI",    meta:1 },
    { nome:"Detergente",                categoria:"ATACADÃO",    unidade:"UNI",    meta:1 },
    // MERCADO
    { nome:"Chocolate para café cliente", categoria:"MERCADO",   unidade:"UNI",    meta:1 },
    { nome:"Cápsula de café",           categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    // VÂNIA
    { nome:"Colher de sobremesa desc.", categoria:"VÂNIA",       unidade:"PACOTE", meta:1 },
    { nome:"Prato de sobremesa desc.",  categoria:"VÂNIA",       unidade:"PACOTE", meta:1 },
    { nome:"Copo descartável",          categoria:"VÂNIA",       unidade:"PACOTE", meta:1 },
    { nome:"Canudo de suco",            categoria:"VÂNIA",       unidade:"PACOTE", meta:1 },
    { nome:"Canudo de drink",           categoria:"VÂNIA",       unidade:"PACOTE", meta:1 },
    { nome:"Sacola para refri 50x50",   categoria:"VÂNIA",       unidade:"PACOTE", meta:1 },
    { nome:"Sachê de açúcar",           categoria:"VÂNIA",       unidade:"CAIXA",  meta:1 },
    { nome:"Sachê de sal",              categoria:"VÂNIA",       unidade:"CAIXA",  meta:1 },
    { nome:"Sachê de adoçante",         categoria:"VÂNIA",       unidade:"CAIXA",  meta:1 },
    { nome:"Palito empacotado",         categoria:"VÂNIA",       unidade:"PACOTE", meta:1 },
    { nome:"Colher para café",          categoria:"VÂNIA",       unidade:"PACOTE", meta:1 },
    // CLORO E CIA
    { nome:"Papel higiênico",           categoria:"CLORO E CIA", unidade:"ROLOS",  meta:1 },
    { nome:"Saco de lixo 200L",         categoria:"CLORO E CIA", unidade:"FARDO",  meta:1 },
    { nome:"Saco de lixo 15L",          categoria:"CLORO E CIA", unidade:"FARDO",  meta:1 },
    { nome:"Álcool em gel",             categoria:"CLORO E CIA", unidade:"LITROS", meta:1 },
    { nome:"Álcool líquido",            categoria:"CLORO E CIA", unidade:"LITROS", meta:1 },
    { nome:"Multiuso perfumado",        categoria:"CLORO E CIA", unidade:"UNI",    meta:1 },
    { nome:"Papel toalha banheiro",     categoria:"CLORO E CIA", unidade:"PACOTE", meta:1 },
    { nome:"Sabonete líquido",          categoria:"CLORO E CIA", unidade:"LITROS", meta:1 },
    { nome:"Guardanapo mesa",           categoria:"CLORO E CIA", unidade:"CAIXA",  meta:1 },
    { nome:"Inseticida",                categoria:"CLORO E CIA", unidade:"UNI",    meta:1 },
    // BEBIDAS
    { nome:"Água sem gás",              categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Água com gás",              categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Coca pet 1L",               categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Coca cola LS 1L",           categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Coca zero pet 1L",          categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Coca lata",                 categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Coca zero lata",            categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Fanta laranja lata",        categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Kuat lata",                 categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Sprite lata",               categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Schweppes citrus",          categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Schweppes tônica",          categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Energético Monster",        categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Del valle uva",             categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Sprite lemon fresh",        categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Amstel 600ml",              categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Heineken 600ml",            categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Heineken long neck",        categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Heineken zero long neck",   categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Sakê garrafa",              categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Rum",                       categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Aperol",                    categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Whiskey Old Parr 12 anos",  categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Whiskey Ballantines 8 anos",categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Vodca Smirnoff",            categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Gin",                       categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Cachaça",                   categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Curaçau blue",              categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Espumante demi sec",        categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Espumante moscatel",        categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    { nome:"Espumante brut rosé",       categoria:"BEBIDAS",     unidade:"UNI",    meta:1 },
    // OUTROS
    { nome:"Hashi",                     categoria:"OUTROS",      unidade:"PCT",    meta:1 },
    { nome:"Espuma de gengibre",        categoria:"OUTROS",      unidade:"UNI",    meta:1 },
    { nome:"Bobina de impressora",      categoria:"OUTROS",      unidade:"UNI",    meta:1 },
    { nome:"Caneta",                    categoria:"OUTROS",      unidade:"UNI",    meta:1 },
    { nome:"Marca texto",               categoria:"OUTROS",      unidade:"UNI",    meta:1 },
    { nome:"Grampo",                    categoria:"OUTROS",      unidade:"CAIXA",  meta:1 },
    { nome:"Piloto",                    categoria:"OUTROS",      unidade:"UNI",    meta:1 },
    { nome:"Bobina de máquina cartão",  categoria:"OUTROS",      unidade:"UNI",    meta:1 },
    { nome:"Embalagem de talher",       categoria:"OUTROS",      unidade:"PCT",    meta:1 },
    { nome:"Adaptador de hashi",        categoria:"OUTROS",      unidade:"PCT",    meta:1 },
    { nome:"Wasabi",                    categoria:"OUTROS",      unidade:"UNI",    meta:1 },
    { nome:"Gengibre em conserva",      categoria:"OUTROS",      unidade:"UNI",    meta:1 },
    { nome:"Amora congelada",           categoria:"OUTROS",      unidade:"PCT",    meta:1 },
    { nome:"Framboesa congelada",       categoria:"OUTROS",      unidade:"PCT",    meta:1 },
    { nome:"Morango congelado",         categoria:"OUTROS",      unidade:"PCT",    meta:1 },
    { nome:"Porções de frutas vermelhas", categoria:"OUTROS",    unidade:"PORÇÃO", meta:1 },
    { nome:"Porções de morango",        categoria:"OUTROS",      unidade:"PORÇÃO", meta:1 },
    { nome:"Porções de maracujá",       categoria:"OUTROS",      unidade:"PORÇÃO", meta:1 },
    { nome:"Porções de abacaxi",        categoria:"OUTROS",      unidade:"PORÇÃO", meta:1 },
    { nome:"Abacaxi sem porcionar",     categoria:"OUTROS",      unidade:"UNI",    meta:1 },
    { nome:"Maracujá sem porcionar",    categoria:"OUTROS",      unidade:"KG",     meta:1 },
  ]),

  ...b(j, "Sushibar", [
    // FEIRA
    { nome:"Acelga",                    categoria:"FEIRA",       unidade:"UNI",    meta:1 },
    { nome:"Chuchu",                    categoria:"FEIRA",       unidade:"UNI",    meta:1 },
    { nome:"Pepino japonês",            categoria:"FEIRA",       unidade:"UNI",    meta:1 },
    { nome:"Manga",                     categoria:"FEIRA",       unidade:"UNI",    meta:1 },
    { nome:"Maçã verde",                categoria:"FEIRA",       unidade:"UNI",    meta:1 },
    // VERDURÃO
    { nome:"Cebola roxa",               categoria:"VERDURÃO",    unidade:"UNI",    meta:1 },
    { nome:"Couve pés",                 categoria:"VERDURÃO",    unidade:"PÉS",    meta:1 },
    { nome:"Couve sacos",               categoria:"VERDURÃO",    unidade:"SACOS",  meta:1 },
    { nome:"Salsa",                     categoria:"VERDURÃO",    unidade:"PÉS",    meta:1 },
    { nome:"Manjericão",                categoria:"VERDURÃO",    unidade:"PÉS",    meta:1 },
    { nome:"Cebolinha",                 categoria:"VERDURÃO",    unidade:"PÉS",    meta:1 },
    // DR SHAPE
    { nome:"Chips de banana",           categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    { nome:"Chips de batata",           categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    { nome:"Chips de mandioca",         categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    { nome:"Mix de castanha",           categoria:"DR SHAPE",    unidade:"GRAMAS", meta:1 },
    // MERCADO
    { nome:"Gengibre",                  categoria:"MERCADO",     unidade:"GRAMAS", meta:1 },
    { nome:"Azeite",                    categoria:"MERCADO",     unidade:"UNI",    meta:1 },
    { nome:"Pimenta de cheiro",         categoria:"MERCADO",     unidade:"GRAMAS", meta:1 },
    // VÂNIA
    { nome:"Goiabada em barra",         categoria:"VÂNIA",       unidade:"UNI",    meta:1 },
    // OUTROS
    { nome:"Queijo mussarela da região",categoria:"OUTROS",      unidade:"BARRA",  meta:1 },
    { nome:"Folha de ouro",             categoria:"OUTROS",      unidade:"UNI",    meta:1 },
    // DEPOSITO
    { nome:"Embalagem de temaki",       categoria:"DEPOSITO",    unidade:"PACOTE", meta:1 },
    { nome:"Embalagem de ceviche",      categoria:"DEPOSITO",    unidade:"PACOTE", meta:1 },
    { nome:"Caixa n1",                  categoria:"DEPOSITO",    unidade:"PACOTE", meta:1 },
    { nome:"Caixa n2",                  categoria:"DEPOSITO",    unidade:"PACOTE", meta:1 },
    { nome:"Caixa n3",                  categoria:"DEPOSITO",    unidade:"PACOTE", meta:1 },
    { nome:"Caixa n4",                  categoria:"DEPOSITO",    unidade:"PACOTE", meta:1 },
    { nome:"Embalagem de poke",         categoria:"DEPOSITO",    unidade:"CAIXA",  meta:1 },
    { nome:"Barca plástica M",          categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Barca plástica G",          categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Sakê culinário",            categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Vinagre de arroz 20L",      categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Shoyu 20L",                 categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Gás para maçarico",         categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Pimenta biquinho",          categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Geleia de pimenta biquinho",categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Cream cheese balde",        categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Salmão",                    categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Camarão sem casca",         categoria:"DEPOSITO",    unidade:"KG",     meta:1 },
    { nome:"Kani",                      categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Peixe branco",              categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Massa de harumaki",         categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Nori",                      categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Arroz japonês",             categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Pimenta sriracha",          categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Ovas de massago",           categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Gergelim preto",            categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Gergelim branco",           categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Hondashi",                  categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Rolo de perfex",            categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Glutamato",                 categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
    { nome:"Doritos",                   categoria:"DEPOSITO",    unidade:"UNI",    meta:1 },
  ]),
];

// ─── Ykedin Capim Grosso ──────────────────────────────────────────────────────

export const CG: ProdutoSeed[] = [
  ...b(cg, "Cozinha", [
    { nome:"Laranja",                   categoria:"FEIRA",       unidade:"KG",     meta:10  },
    { nome:"Repolho branco",            categoria:"FEIRA",       unidade:"UNI",    meta:10  },
    { nome:"Repolho roxo",              categoria:"FEIRA",       unidade:"UNI",    meta:15  },
    { nome:"Cenoura",                   categoria:"FEIRA",       unidade:"KG",     meta:12  },
    { nome:"Banana da terra",           categoria:"FEIRA",       unidade:"UNI",    meta:12  },
    { nome:"Cebola branca",             categoria:"FEIRA",       unidade:"KG",     meta:10  },
    { nome:"Tomate maduros e firmes",   categoria:"FEIRA",       unidade:"UNI",    meta:40  },
    { nome:"Batatinha",                 categoria:"FEIRA",       unidade:"UNI",    meta:30  },
    { nome:"Brócolis",                  categoria:"FEIRA",       unidade:"UNI",    meta:6   },
    { nome:"Morango fresco",            categoria:"FEIRA",       unidade:"KG",     meta:5   },
    { nome:"Coentro",                   categoria:"VERDURÃO",    unidade:"PÉS",    meta:3   },
    { nome:"Pimentão vermelho",         categoria:"VERDURÃO",    unidade:"UNI",    meta:6   },
    { nome:"Pimentão verde",            categoria:"VERDURÃO",    unidade:"UNI",    meta:8   },
    { nome:"Alface",                    categoria:"VERDURÃO",    unidade:"PÉS",    meta:2   },
    { nome:"Castanha",                  categoria:"DR SHAPE",    unidade:"GRAMAS", meta:300 },
    { nome:"Castanha triturada",        categoria:"DR SHAPE",    unidade:"GRAMAS", meta:300 },
    { nome:"Cominho",                   categoria:"DR SHAPE",    unidade:"GRAMAS", meta:300 },
    { nome:"Orégano",                   categoria:"DR SHAPE",    unidade:"GRAMAS", meta:300 },
    { nome:"Pimenta do reino",          categoria:"DR SHAPE",    unidade:"GRAMAS", meta:300 },
    { nome:"Canela em pó",              categoria:"DR SHAPE",    unidade:"GRAMAS", meta:300 },
    { nome:"Lemon pepper",              categoria:"DR SHAPE",    unidade:"GRAMAS", meta:200 },
    { nome:"Corante",                   categoria:"DR SHAPE",    unidade:"GRAMAS", meta:300 },
    { nome:"Açúcar",                    categoria:"ATACADÃO",    unidade:"UNI",    meta:20  },
    { nome:"Óleo",                      categoria:"ATACADÃO",    unidade:"UNI",    meta:12  },
    { nome:"Farinha de trigo",          categoria:"ATACADÃO",    unidade:"UNI",    meta:10  },
    { nome:"Arroz",                     categoria:"ATACADÃO",    unidade:"UNI",    meta:8   },
    { nome:"Papel toalha",              categoria:"ATACADÃO",    unidade:"UNI",    meta:24  },
    { nome:"Bombril",                   categoria:"ATACADÃO",    unidade:"UNI",    meta:1   },
    { nome:"Leite",                     categoria:"ATACADÃO",    unidade:"UNI",    meta:15  },
    { nome:"Presunto",                  categoria:"MERCADO",     unidade:"UNI",    meta:1   },
    { nome:"Extrato elefante",          categoria:"MERCADO",     unidade:"UNI",    meta:4   },
    { nome:"Maionese",                  categoria:"MERCADO",     unidade:"UNI",    meta:4   },
    { nome:"Café",                      categoria:"MERCADO",     unidade:"UNI",    meta:6   },
    { nome:"Macarrão ninho",            categoria:"MERCADO",     unidade:"UNI",    meta:3   },
    { nome:"Sorvete",                   categoria:"MERCADO",     unidade:"UNI",    meta:8   },
    { nome:"Ovos",                      categoria:"MERCADO",     unidade:"PLACAS", meta:2   },
    { nome:"Veja",                      categoria:"MERCADO",     unidade:"UNI",    meta:2   },
    { nome:"Vinagre",                   categoria:"MERCADO",     unidade:"UNI",    meta:2   },
    { nome:"Isqueiro",                  categoria:"MERCADO",     unidade:"UNI",    meta:4   },
    { nome:"Feijão",                    categoria:"MERCADO",     unidade:"UNI",    meta:2   },
    { nome:"Caldo de legumes",          categoria:"MERCADO",     unidade:"UNI",    meta:1   },
    { nome:"Nescal",                    categoria:"MERCADO",     unidade:"UNI",    meta:2   },
    { nome:"Sal",                       categoria:"MERCADO",     unidade:"UNI",    meta:4   },
    { nome:"Caldo de galinha Knorr",    categoria:"MERCADO",     unidade:"UNI",    meta:12  },
    { nome:"Fermento químico",          categoria:"MERCADO",     unidade:"UNI",    meta:1   },
    { nome:"Embalagem rolinho",         categoria:"VÂNIA",       unidade:"UNI",    meta:1   },
    { nome:"Saco de congelamento 1kg",  categoria:"VÂNIA",       unidade:"UNI",    meta:2   },
    { nome:"Saco de congelamento 5kg",  categoria:"VÂNIA",       unidade:"UNI",    meta:2   },
    { nome:"Calda de chocolate para sorvete", categoria:"VÂNIA", unidade:"UNI",    meta:1   },
    { nome:"Plástico filme grande",     categoria:"VÂNIA",       unidade:"UNI",    meta:1   },
    { nome:"Cereja",                    categoria:"VÂNIA",       unidade:"UNI",    meta:2   },
    { nome:"Bicarbonato de sódio",      categoria:"VÂNIA",       unidade:"UNI",    meta:1   },
    { nome:"Toucas",                    categoria:"VÂNIA",       unidade:"UNI",    meta:1   },
    { nome:"Luva P",                    categoria:"VÂNIA",       unidade:"UNI",    meta:1   },
    { nome:"Luvas M",                   categoria:"VÂNIA",       unidade:"UNI",    meta:1   },
    { nome:"Luvas G",                   categoria:"VÂNIA",       unidade:"UNI",    meta:1   },
    { nome:"Luvas GG",                  categoria:"VÂNIA",       unidade:"UNI",    meta:1   },
    { nome:"Doce de leite",             categoria:"VÂNIA",       unidade:"UNI",    meta:2   },
    { nome:"Corante vermelho bordô em pó", categoria:"VÂNIA",    unidade:"UNI",    meta:2   },
    { nome:"Chocolate em barra",        categoria:"VÂNIA",       unidade:"UNI",    meta:4   },
    { nome:"Amido de milho",            categoria:"VÂNIA",       unidade:"UNI",    meta:6   },
    { nome:"Essência de baunilha",      categoria:"VÂNIA",       unidade:"UNI",    meta:1   },
    { nome:"Chocolate 70%",             categoria:"VÂNIA",       unidade:"UNI",    meta:2   },
    { nome:"Papel manteiga",            categoria:"VÂNIA",       unidade:"UNI",    meta:1   },
    { nome:"Saco de confeiteiro",       categoria:"VÂNIA",       unidade:"UNI",    meta:5   },
    { nome:"Açúcar refinado",           categoria:"VÂNIA",       unidade:"UNI",    meta:5   },
    { nome:"Catchup",                   categoria:"VÂNIA",       unidade:"UNI",    meta:1   },
    { nome:"Garfo descartável reforçado", categoria:"VÂNIA",     unidade:"UNI",    meta:1   },
    { nome:"Faca descartável reforçado",  categoria:"VÂNIA",     unidade:"UNI",    meta:1   },
    { nome:"Pote de 530ml com tampa",   categoria:"VÂNIA",       unidade:"UNI",    meta:1   },
    { nome:"Caneta em gel",             categoria:"VÂNIA",       unidade:"UNI",    meta:2   },
    { nome:"Desengordurante",           categoria:"CLORO E CIA", unidade:"UNI",    meta:1   },
    { nome:"Desincrustante",            categoria:"CLORO E CIA", unidade:"UNI",    meta:1   },
    { nome:"Fibraço",                   categoria:"CLORO E CIA", unidade:"UNI",    meta:2   },
    { nome:"Carne",                     categoria:"PEDRO",       unidade:"KG",     meta:0   },
    { nome:"Manteiga",                  categoria:"PEDRO",       unidade:"KG",     meta:0   },
    { nome:"Queijo mussarela da região",categoria:"PEDRO",       unidade:"BARRA",  meta:0   },
    { nome:"Macarrão Ykedin",           categoria:"PEDRO",       unidade:"UNI",    meta:10  },
    { nome:"Shoyu sachê",               categoria:"PEDRO",       unidade:"CAIXA",  meta:1   },
    { nome:"Berço para shoyu",          categoria:"PEDRO",       unidade:"CAIXA",  meta:1   },
    { nome:"Tonkatsu",                  categoria:"PEDRO",       unidade:"UNI",    meta:1   },
    { nome:"Panko",                     categoria:"PEDRO",       unidade:"UNI",    meta:6   },
    { nome:"Alho descascado",           categoria:"PEDRO",       unidade:"UNI",    meta:0   },
    { nome:"Óleo de algodão",           categoria:"PEDRO",       unidade:"UNI",    meta:0   },
    { nome:"Óleo de gergelim",          categoria:"PEDRO",       unidade:"UNI",    meta:1   },
    { nome:"Shimeji",                   categoria:"PEDRO",       unidade:"PLACAS", meta:10  },
    { nome:"Batata palito",             categoria:"DINE",        unidade:"UNI",    meta:5   },
    { nome:"Peito de frango",           categoria:"DINE",        unidade:"KG",     meta:10  },
    { nome:"Camarão com casca",         categoria:"LUIZ",        unidade:"KG",     meta:5   },
    { nome:"Pote para balls",           categoria:"LUIZ",        unidade:"PACOTE", meta:4   },
    { nome:"Lacre Ykedin",              categoria:"LUIZ",        unidade:"ROLO",   meta:2   },
    { nome:"Sacola craft Ykedin",       categoria:"LUIZ",        unidade:"PACOTE", meta:2   },
    { nome:"Sacola craft poke",         categoria:"LUIZ",        unidade:"PACOTE", meta:1   },
    { nome:"Lacre Poke",                categoria:"LUIZ",        unidade:"ROLO",   meta:1   },
  ]),

  ...b(cg, "Atendimento", [
    { nome:"Limão taiti",               categoria:"FEIRA",       unidade:"KG",     meta:15   },
    { nome:"Abacaxi",                   categoria:"FEIRA",       unidade:"UNI",    meta:0    },
    { nome:"Maracujá",                  categoria:"FEIRA",       unidade:"KG",     meta:0    },
    { nome:"Uva verde",                 categoria:"FEIRA",       unidade:"GRAMAS", meta:1000 },
    { nome:"Morango fresco atend.",     categoria:"FEIRA",       unidade:"PLACAS", meta:0    },
    { nome:"Hortelã",                   categoria:"VERDURÃO",    unidade:"PÉS",    meta:3    },
    { nome:"Canela lasca",              categoria:"DR SHAPE",    unidade:"GRAMAS", meta:0    },
    { nome:"Albumina",                  categoria:"DR SHAPE",    unidade:"GRAMAS", meta:100  },
    { nome:"Anis estrelado",            categoria:"DR SHAPE",    unidade:"GRAMAS", meta:200  },
    { nome:"Bucha",                     categoria:"ATACADÃO",    unidade:"UNI",    meta:10   },
    { nome:"Água sanitária",            categoria:"ATACADÃO",    unidade:"UNI",    meta:30   },
    { nome:"Sabão em pó",               categoria:"ATACADÃO",    unidade:"UNI",    meta:10   },
    { nome:"Detergente",                categoria:"ATACADÃO",    unidade:"UNI",    meta:20   },
    { nome:"Chocolate para café cliente", categoria:"MERCADO",   unidade:"UNI",    meta:0    },
    { nome:"Cápsula de café",           categoria:"MERCADO",     unidade:"UNI",    meta:15   },
    { nome:"Colher de sobremesa desc.", categoria:"VÂNIA",       unidade:"PACOTE", meta:2    },
    { nome:"Prato de sobremesa desc.",  categoria:"VÂNIA",       unidade:"PACOTE", meta:2    },
    { nome:"Copo descartável",          categoria:"VÂNIA",       unidade:"PACOTE", meta:1    },
    { nome:"Canudo de suco",            categoria:"VÂNIA",       unidade:"PACOTE", meta:1    },
    { nome:"Canudo de drink",           categoria:"VÂNIA",       unidade:"PACOTE", meta:1    },
    { nome:"Sacola para refri 50x50",   categoria:"VÂNIA",       unidade:"PACOTE", meta:2    },
    { nome:"Sachê de açúcar",           categoria:"VÂNIA",       unidade:"CAIXA",  meta:1    },
    { nome:"Sachê de sal",              categoria:"VÂNIA",       unidade:"CAIXA",  meta:1    },
    { nome:"Sachê de adoçante",         categoria:"VÂNIA",       unidade:"CAIXA",  meta:1    },
    { nome:"Palito empacotado",         categoria:"VÂNIA",       unidade:"CAIXA",  meta:1    },
    { nome:"Colher para café",          categoria:"VÂNIA",       unidade:"PACOTE", meta:1    },
    { nome:"Papel higiênico",           categoria:"CLORO E CIA", unidade:"ROLOS",  meta:4    },
    { nome:"Saco de lixo 200L",         categoria:"CLORO E CIA", unidade:"FARDO",  meta:1    },
    { nome:"Saco de lixo 15L",          categoria:"CLORO E CIA", unidade:"FARDO",  meta:1    },
    { nome:"Álcool em gel",             categoria:"CLORO E CIA", unidade:"LITROS", meta:1    },
    { nome:"Álcool líquido",            categoria:"CLORO E CIA", unidade:"LITROS", meta:10   },
    { nome:"Multiuso perfumado",        categoria:"CLORO E CIA", unidade:"UNI",    meta:1    },
    { nome:"Papel toalha banheiro",     categoria:"CLORO E CIA", unidade:"PACOTE", meta:1    },
    { nome:"Sabonete líquido",          categoria:"CLORO E CIA", unidade:"LITROS", meta:2    },
    { nome:"Guardanapo mesa",           categoria:"CLORO E CIA", unidade:"CAIXA",  meta:1    },
    { nome:"Inseticida",                categoria:"CLORO E CIA", unidade:"UNI",    meta:1    },
    { nome:"Água sem gás",              categoria:"BEBIDAS",     unidade:"UNI",    meta:36   },
    { nome:"Água com gás",              categoria:"BEBIDAS",     unidade:"UNI",    meta:36   },
    { nome:"Coca pet 1L",               categoria:"BEBIDAS",     unidade:"UNI",    meta:24   },
    { nome:"Coca cola LS 1L",           categoria:"BEBIDAS",     unidade:"UNI",    meta:12   },
    { nome:"Coca zero pet 1L",          categoria:"BEBIDAS",     unidade:"UNI",    meta:0    },
    { nome:"Coca lata",                 categoria:"BEBIDAS",     unidade:"UNI",    meta:24   },
    { nome:"Coca zero lata",            categoria:"BEBIDAS",     unidade:"UNI",    meta:24   },
    { nome:"Fanta laranja lata",        categoria:"BEBIDAS",     unidade:"UNI",    meta:12   },
    { nome:"Kuat lata",                 categoria:"BEBIDAS",     unidade:"UNI",    meta:12   },
    { nome:"Sprite lata",               categoria:"BEBIDAS",     unidade:"UNI",    meta:12   },
    { nome:"Schweppes citrus",          categoria:"BEBIDAS",     unidade:"UNI",    meta:12   },
    { nome:"Schweppes tônica",          categoria:"BEBIDAS",     unidade:"UNI",    meta:12   },
    { nome:"Energético Monster",        categoria:"BEBIDAS",     unidade:"UNI",    meta:12   },
    { nome:"Del valle uva",             categoria:"BEBIDAS",     unidade:"UNI",    meta:12   },
    { nome:"Sprite lemon fresh",        categoria:"BEBIDAS",     unidade:"UNI",    meta:24   },
    { nome:"Amstel 600ml",              categoria:"BEBIDAS",     unidade:"UNI",    meta:50   },
    { nome:"Heineken 600ml",            categoria:"BEBIDAS",     unidade:"UNI",    meta:50   },
    { nome:"Heineken long neck",        categoria:"BEBIDAS",     unidade:"UNI",    meta:24   },
    { nome:"Heineken zero long neck",   categoria:"BEBIDAS",     unidade:"UNI",    meta:24   },
    { nome:"Sakê garrafa",              categoria:"BEBIDAS",     unidade:"UNI",    meta:3    },
    { nome:"Rum",                       categoria:"BEBIDAS",     unidade:"UNI",    meta:2    },
    { nome:"Aperol",                    categoria:"BEBIDAS",     unidade:"UNI",    meta:2    },
    { nome:"Whiskey Old Parr 12 anos",  categoria:"BEBIDAS",     unidade:"UNI",    meta:2    },
    { nome:"Whiskey Ballantines 8 anos",categoria:"BEBIDAS",     unidade:"UNI",    meta:1    },
    { nome:"Vodca Smirnoff",            categoria:"BEBIDAS",     unidade:"UNI",    meta:1    },
    { nome:"Gin",                       categoria:"BEBIDAS",     unidade:"UNI",    meta:2    },
    { nome:"Cachaça",                   categoria:"BEBIDAS",     unidade:"UNI",    meta:1    },
    { nome:"Curaçau blue",              categoria:"BEBIDAS",     unidade:"UNI",    meta:1    },
    { nome:"Espumante demi sec",        categoria:"BEBIDAS",     unidade:"UNI",    meta:12   },
    { nome:"Espumante moscatel",        categoria:"BEBIDAS",     unidade:"UNI",    meta:12   },
    { nome:"Espumante brut rosé",       categoria:"BEBIDAS",     unidade:"UNI",    meta:12   },
    { nome:"Hashi",                     categoria:"OUTROS",      unidade:"PCT",    meta:0    },
    { nome:"Embalagem de talher (c/100)",categoria:"OUTROS",     unidade:"PCT",    meta:0    },
    { nome:"Espuma de gengibre",        categoria:"OUTROS",      unidade:"UNI",    meta:0    },
    { nome:"Amora congelada",           categoria:"OUTROS",      unidade:"PCT",    meta:2    },
    { nome:"Framboesa congelada",       categoria:"OUTROS",      unidade:"PCT",    meta:2    },
    { nome:"Morango congelado",         categoria:"OUTROS",      unidade:"PCT",    meta:10   },
    { nome:"Porções de frutas vermelhas",categoria:"OUTROS",     unidade:"PORÇÃO", meta:0    },
    { nome:"Porções de morango",        categoria:"OUTROS",      unidade:"PORÇÃO", meta:0    },
    { nome:"Adaptador de hashi",        categoria:"PEDRO",       unidade:"PCT",    meta:0    },
    { nome:"Wasabi",                    categoria:"PEDRO",       unidade:"UNI",    meta:1    },
    { nome:"Gengibre em conserva",      categoria:"PEDRO",       unidade:"UNI",    meta:1    },
  ]),

  ...b(cg, "Sushibar", [
    { nome:"Acelga",                    categoria:"FEIRA",       unidade:"UNI",    meta:4   },
    { nome:"Chuchu",                    categoria:"FEIRA",       unidade:"UNI",    meta:20  },
    { nome:"Pepino japonês",            categoria:"FEIRA",       unidade:"UNI",    meta:10  },
    { nome:"Manga",                     categoria:"FEIRA",       unidade:"UNI",    meta:10  },
    { nome:"Maçã verde",                categoria:"FEIRA",       unidade:"UNI",    meta:15  },
    { nome:"Cebola roxa",               categoria:"VERDURÃO",    unidade:"UNI",    meta:10  },
    { nome:"Couve pés",                 categoria:"VERDURÃO",    unidade:"PÉS",    meta:10  },
    { nome:"Couve sacos",               categoria:"VERDURÃO",    unidade:"SACOS",  meta:10  },
    { nome:"Salsa",                     categoria:"VERDURÃO",    unidade:"PÉS",    meta:1   },
    { nome:"Manjericão",                categoria:"VERDURÃO",    unidade:"PÉS",    meta:1   },
    { nome:"Cebolinha",                 categoria:"VERDURÃO",    unidade:"PÉS",    meta:15  },
    { nome:"Chips de banana",           categoria:"DR SHAPE",    unidade:"GRAMAS", meta:300 },
    { nome:"Chips de batata",           categoria:"DR SHAPE",    unidade:"GRAMAS", meta:300 },
    { nome:"Chips de mandioca",         categoria:"DR SHAPE",    unidade:"GRAMAS", meta:300 },
    { nome:"Mix de castanha",           categoria:"DR SHAPE",    unidade:"GRAMAS", meta:300 },
    { nome:"Gengibre",                  categoria:"MERCADO",     unidade:"GRAMAS", meta:300 },
    { nome:"Azeite",                    categoria:"MERCADO",     unidade:"UNI",    meta:2   },
    { nome:"Pimenta de cheiro",         categoria:"MERCADO",     unidade:"GRAMAS", meta:200 },
    { nome:"Goiabada em barra",         categoria:"VÂNIA",       unidade:"UNI",    meta:3   },
    { nome:"Folha de ouro",             categoria:"OUTROS",      unidade:"UNI",    meta:1   },
    { nome:"Queijo mussarela sushi",    categoria:"PEDRO",       unidade:"BARRA",  meta:0   },
    { nome:"Arroz japonês",             categoria:"PEDRO",       unidade:"UNI",    meta:2   },
    { nome:"Massa de harumaki",         categoria:"PEDRO",       unidade:"UNI",    meta:10  },
    { nome:"Nori",                      categoria:"PEDRO",       unidade:"UNI",    meta:6   },
    { nome:"Pimenta sriracha",          categoria:"PEDRO",       unidade:"UNI",    meta:1   },
    { nome:"Gergelim preto",            categoria:"PEDRO",       unidade:"UNI",    meta:1   },
    { nome:"Gergelim branco",           categoria:"PEDRO",       unidade:"UNI",    meta:1   },
    { nome:"Hondashi",                  categoria:"PEDRO",       unidade:"UNI",    meta:1   },
    { nome:"Rolo de perfex",            categoria:"PEDRO",       unidade:"UNI",    meta:1   },
    { nome:"Glutamato",                 categoria:"PEDRO",       unidade:"UNI",    meta:1   },
    { nome:"Sakê culinário",            categoria:"PEDRO",       unidade:"UNI",    meta:1   },
    { nome:"Vinagre de arroz 20L",      categoria:"PEDRO",       unidade:"UNI",    meta:1   },
    { nome:"Shoyu 20L",                 categoria:"PEDRO",       unidade:"UNI",    meta:1   },
    { nome:"Gás para maçarico",         categoria:"PEDRO",       unidade:"UNI",    meta:2   },
    { nome:"Pimenta biquinho",          categoria:"PEDRO",       unidade:"UNI",    meta:1   },
    { nome:"Geleia de pimenta biquinho",categoria:"PEDRO",       unidade:"UNI",    meta:1   },
    { nome:"Cream cheese",              categoria:"PEDRO",       unidade:"UNI",    meta:7   },
    { nome:"Barca plástica M",          categoria:"PEDRO",       unidade:"UNI",    meta:0   },
    { nome:"Barca plástica G",          categoria:"PEDRO",       unidade:"UNI",    meta:0   },
    { nome:"Embalagem de poke",         categoria:"PEDRO",       unidade:"CAIXA",  meta:0   },
    { nome:"Doritos",                   categoria:"DINE",        unidade:"UNI",    meta:5   },
    { nome:"Camarão sem casca",         categoria:"LUIZ",        unidade:"KG",     meta:15  },
    { nome:"Salmão",                    categoria:"LUIZ",        unidade:"UNI",    meta:17  },
    { nome:"Kani",                      categoria:"LUIZ",        unidade:"UNI",    meta:7   },
    { nome:"Ovas de massago",           categoria:"LUIZ",        unidade:"UNI",    meta:2   },
    { nome:"Peixe branco",              categoria:"LUIZ",        unidade:"UNI",    meta:2   },
    { nome:"Embalagem de temaki",       categoria:"LUIZ",        unidade:"PACOTE", meta:3   },
    { nome:"Embalagem de ceviche",      categoria:"LUIZ",        unidade:"PACOTE", meta:2   },
    { nome:"Caixa n1",                  categoria:"LUIZ",        unidade:"PACOTE", meta:2   },
    { nome:"Caixa n2",                  categoria:"LUIZ",        unidade:"PACOTE", meta:2   },
    { nome:"Caixa n3",                  categoria:"LUIZ",        unidade:"PACOTE", meta:2   },
    { nome:"Caixa n4",                  categoria:"LUIZ",        unidade:"PACOTE", meta:2   },
  ]),
];

// ─── Deck ─────────────────────────────────────────────────────────────────────

export const DECK: ProdutoSeed[] = [
  ...b(dk, "Cozinha", [
    { nome:"Laranja",       categoria:"FEIRA",    unidade:"KG",  meta:1 },
    { nome:"Limão Taiti",   categoria:"FEIRA",    unidade:"KG",  meta:1 },
    { nome:"Cebola Branca", categoria:"FEIRA",    unidade:"KG",  meta:1 },
    { nome:"Tomate",        categoria:"FEIRA",    unidade:"KG",  meta:1 },
    { nome:"Cenoura",       categoria:"VERDURÃO", unidade:"KG",  meta:1 },
    { nome:"Alface",        categoria:"VERDURÃO", unidade:"UNI", meta:1 },
    { nome:"Sal",           categoria:"MERCADO",  unidade:"UNI", meta:1 },
    { nome:"Óleo",          categoria:"MERCADO",  unidade:"UNI", meta:1 },
    { nome:"Arroz",         categoria:"ATACADÃO", unidade:"UNI", meta:1 },
    { nome:"Açúcar",        categoria:"ATACADÃO", unidade:"UNI", meta:1 },
  ]),
];

// ─── Seed function ────────────────────────────────────────────────────────────

type DB = {
  $queryRawUnsafe<T = unknown>(query: string, ...values: unknown[]): Promise<T>;
  $executeRawUnsafe(query: string, ...values: unknown[]): Promise<number>;
};

async function insertAll(db: DB, products: ProdutoSeed[]) {
  for (const p of products) {
    const id = randomUUID();
    await db.$executeRawUnsafe(
      `INSERT OR IGNORE INTO "ProdutoEstoque"
         ("id","nome","categoria","unidade","quantidadeAtual","quantidadeMinima",
          "metaSemanal","qtdPorPacote","ilimitado","sacaThresholdCheia","sacaThresholdMeia",
          "restaurante","ordemCategoria","setor")
       VALUES (?,?,?,?,0,0,?,1,0,null,null,?,?,?)`,
      id, p.nome, p.categoria, p.unidade, p.meta,
      p.restaurante, CAT_ORDER[p.categoria] ?? 99, p.setor,
    );
  }
}

export async function seedProdutos(db: DB) {
  const counts = await db.$queryRawUnsafe<{ restaurante: string | null; total: unknown }[]>(
    `SELECT restaurante, COUNT(*) as total FROM "ProdutoEstoque" WHERE ativo=1 GROUP BY restaurante`,
  );
  const existing = Object.fromEntries(counts.map((r) => [r.restaurante ?? "", Number(r.total)]));
  const total = Object.values(existing).reduce((s, v) => s + v, 0);

  // If all existing products still have default setor, wipe and reseed with correct setores
  if (total > 0) {
    const semSetor = await db.$queryRawUnsafe<{ n: unknown }[]>(
      `SELECT COUNT(*) as n FROM "ProdutoEstoque" WHERE ativo=1 AND setor='Geral'`,
    );
    const countSemSetor = Number(semSetor[0]?.n ?? 0);
    if (countSemSetor === total) {
      await db.$executeRawUnsafe(`DELETE FROM "ContagemSemanal"`);
      await db.$executeRawUnsafe(`DELETE FROM "HistoricoEstoque"`);
      await db.$executeRawUnsafe(`DELETE FROM "ProdutoEstoque"`);
      await insertAll(db, [...JACOBINA, ...CG, ...DECK]);
      return JACOBINA.length + CG.length + DECK.length;
    }
  }

  // Normal first-time seed — only insert missing restaurants
  const toInsert: ProdutoSeed[] = [];
  if (!existing["Ykedin Jacobina"]) toInsert.push(...JACOBINA);
  if (!existing["Ykedin Capim Grosso"]) toInsert.push(...CG);
  if (!existing["Deck"]) toInsert.push(...DECK);

  await insertAll(db, toInsert);
  return toInsert.length;
}
